### ISSUE TITLE
資料置き場

### ISSUE THREAD

**Issue by yosuke-furukawa** [meta-sushi/guideline#2]
寿司資料置き場作る際に、meta-sushi/presentation リポジトリがほしい

**Comment by azu** [comment]
> meta-sushi/presentation というリポジトリを作ってファイルを置きたいときはそこを使う

ファイル置き場としてリポジトリがあるのは便利だと思うので :+1: 

ただGitHubに置けない資料とかの場合とか、イベントの資料をまとめたり的な用途だと[Home · potatotips/potatotips Wiki](https://github.com/potatotips/potatotips/wiki) みたいにリンクをまとめる感じでも良さそうな気がしますね。(Wikiを併用するとか)

基本的に絶対という規約はないので、自由に使える場所としてあるというイメージですかね。

**Comment by twada** [comment]
:+1:

**Comment by hokaccha** [comment]
僕もWikiにイベントのまとめみたいのを残していくほうに +1 です。

**Comment by azu** [comment]
presentation だと名前的にガイドラインに反する気がするので、

> LTは口頭のみで資料がなくても良い

meta-sushi/event か meta-sushi/meta-sushi にリポジトリ作ろうと思います。

**Comment by yosuke-furukawa** [comment]
:+1:

**Comment by azu** [comment]
land! https://github.com/meta-sushi/event
